# Generated by Django 3.2.5 on 2022-01-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealer',
            name='image',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='role',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Administrator'), ('3', 'Vendor')], default='1', max_length=23),
        ),
    ]
