# Generated by Django 3.2.5 on 2022-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20220127_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='role',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Administrator'), ('3', 'Vendor')], max_length=23),
        ),
    ]
