# Generated by Django 3.2.5 on 2022-01-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_dealer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
