# Generated by Django 3.2.5 on 2022-02-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.dealer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_photo',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
