# Generated by Django 3.2.5 on 2022-02-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_vehicle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(default=None, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
