# Generated by Django 3.2.5 on 2022-02-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20220207_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='citizenship_back',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='citizenship_front',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driving_license',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
