# Generated by Django 3.2.5 on 2022-02-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_auto_20220207_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
