# Generated by Django 3.2.5 on 2022-02-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='endtime',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='starttime',
            field=models.DateField(default=None),
        ),
    ]
