# Generated by Django 3.2.5 on 2022-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_vehicle_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50, null=True)),
                ('longitude', models.CharField(max_length=50, null=True)),
                ('count', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
